update=9/29/2018 12:47:06 AM
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=power
LibName2=device
LibName3=transistors
LibName4=conn
LibName5=linear
LibName6=regul
LibName7=74xx
LibName8=cmos4000
LibName9=adc-dac
LibName10=memory
LibName11=xilinx
LibName12=microcontrollers
LibName13=dsp
LibName14=microchip
LibName15=analog_switches
LibName16=motorola
LibName17=texas
LibName18=intel
LibName19=audio
LibName20=interface
LibName21=digital-audio
LibName22=philips
LibName23=display
LibName24=cypress
LibName25=siliconi
LibName26=opto
LibName27=atmel
LibName28=contrib
LibName29=valves
LibName30=C:/projects/PCB-Libraries/KiCAD/µ104_Part_Libs/schematicComponents/u104_KICAD_adc-dac
LibName31=C:/projects/PCB-Libraries/KiCAD/µ104_Part_Libs/schematicComponents/u104_KICAD_dcdc
LibName32=C:/projects/PCB-Libraries/KiCAD/µ104_Part_Libs/schematicComponents/u104_KICAD_logic
LibName33=C:/projects/PCB-Libraries/KiCAD/µ104_Part_Libs/schematicComponents/u104_KICAD_mcu
LibName34=C:/projects/PCB-Libraries/KiCAD/µ104_Part_Libs/schematicComponents/u104_KICAD_misc
LibName35=C:/projects/PCB-Libraries/KiCAD/µ104_Part_Libs/schematicComponents/u104_KICAD_pwr
LibName36=C:/projects/PCB-Libraries/KiCAD/µ104_Part_Libs/schematicComponents/u104_KICAD_pwrMgmt
LibName37=C:/projects/PCB-Libraries/KiCAD/µ104_Part_Libs/schematicComponents/u104_KICAD_relay
LibName38=C:/projects/PCB-Libraries/KiCAD/µ104_Part_Libs/schematicComponents/u104_KICAD_sensor
LibName39=C:/projects/PCB-Libraries/KiCAD/µ104_Part_Libs/schematicComponents/u104_KICAD_transceiver
LibName40=S:/Program Files/KiCad/share/kicad/library/74xgxx
LibName41=S:/Program Files/KiCad/share/kicad/library/74xx
LibName42=S:/Program Files/KiCad/share/kicad/library/ac-dc
LibName43=S:/Program Files/KiCad/share/kicad/library/actel
LibName44=S:/Program Files/KiCad/share/kicad/library/adc-dac
LibName45=S:/Program Files/KiCad/share/kicad/library/allegro
LibName46=S:/Program Files/KiCad/share/kicad/library/Altera
LibName47=S:/Program Files/KiCad/share/kicad/library/analog_devices
LibName48=S:/Program Files/KiCad/share/kicad/library/analog_switches
LibName49=S:/Program Files/KiCad/share/kicad/library/atmel
LibName50=S:/Program Files/KiCad/share/kicad/library/audio
LibName51=S:/Program Files/KiCad/share/kicad/library/battery_management
LibName52=S:/Program Files/KiCad/share/kicad/library/bbd
LibName53=S:/Program Files/KiCad/share/kicad/library/bosch
LibName54=S:/Program Files/KiCad/share/kicad/library/brooktre
LibName55=S:/Program Files/KiCad/share/kicad/library/cmos_ieee
LibName56=S:/Program Files/KiCad/share/kicad/library/cmos4000
LibName57=S:/Program Files/KiCad/share/kicad/library/conn
LibName58=S:/Program Files/KiCad/share/kicad/library/contrib
LibName59=S:/Program Files/KiCad/share/kicad/library/cypress
LibName60=S:/Program Files/KiCad/share/kicad/library/dc-dc
LibName61=S:/Program Files/KiCad/share/kicad/library/device
LibName62=S:/Program Files/KiCad/share/kicad/library/digital-audio
LibName63=S:/Program Files/KiCad/share/kicad/library/diode
LibName64=S:/Program Files/KiCad/share/kicad/library/display
LibName65=S:/Program Files/KiCad/share/kicad/library/dsp
LibName66=S:/Program Files/KiCad/share/kicad/library/elec-unifil
LibName67=S:/Program Files/KiCad/share/kicad/library/ESD_Protection
LibName68=S:/Program Files/KiCad/share/kicad/library/ftdi
LibName69=S:/Program Files/KiCad/share/kicad/library/gennum
LibName70=S:/Program Files/KiCad/share/kicad/library/graphic_symbols
LibName71=S:/Program Files/KiCad/share/kicad/library/hc11
LibName72=S:/Program Files/KiCad/share/kicad/library/infineon
LibName73=S:/Program Files/KiCad/share/kicad/library/intel
LibName74=S:/Program Files/KiCad/share/kicad/library/interface
LibName75=S:/Program Files/KiCad/share/kicad/library/intersil
LibName76=S:/Program Files/KiCad/share/kicad/library/ir
LibName77=S:/Program Files/KiCad/share/kicad/library/Lattice
LibName78=S:/Program Files/KiCad/share/kicad/library/leds
LibName79=S:/Program Files/KiCad/share/kicad/library/LEM
LibName80=S:/Program Files/KiCad/share/kicad/library/linear
LibName81=S:/Program Files/KiCad/share/kicad/library/logic_programmable
LibName82=S:/Program Files/KiCad/share/kicad/library/maxim
LibName83=S:/Program Files/KiCad/share/kicad/library/mechanical
LibName84=S:/Program Files/KiCad/share/kicad/library/memory
LibName85=S:/Program Files/KiCad/share/kicad/library/microchip
LibName86=S:/Program Files/KiCad/share/kicad/library/microchip_dspic33dsc
LibName87=S:/Program Files/KiCad/share/kicad/library/microchip_pic10mcu
LibName88=S:/Program Files/KiCad/share/kicad/library/microchip_pic12mcu
LibName89=S:/Program Files/KiCad/share/kicad/library/microchip_pic16mcu
LibName90=S:/Program Files/KiCad/share/kicad/library/microchip_pic18mcu
LibName91=S:/Program Files/KiCad/share/kicad/library/microchip_pic24mcu
LibName92=S:/Program Files/KiCad/share/kicad/library/microchip_pic32mcu
LibName93=S:/Program Files/KiCad/share/kicad/library/microcontrollers
LibName94=S:/Program Files/KiCad/share/kicad/library/modules
LibName95=S:/Program Files/KiCad/share/kicad/library/motor_drivers
LibName96=S:/Program Files/KiCad/share/kicad/library/motorola
LibName97=S:/Program Files/KiCad/share/kicad/library/motors
LibName98=S:/Program Files/KiCad/share/kicad/library/msp430
LibName99=S:/Program Files/KiCad/share/kicad/library/nordicsemi
LibName100=S:/Program Files/KiCad/share/kicad/library/nxp
LibName101=S:/Program Files/KiCad/share/kicad/library/nxp_armmcu
LibName102=S:/Program Files/KiCad/share/kicad/library/onsemi
LibName103=S:/Program Files/KiCad/share/kicad/library/opto
LibName104=S:/Program Files/KiCad/share/kicad/library/Oscillators
LibName105=S:/Program Files/KiCad/share/kicad/library/philips
LibName106=S:/Program Files/KiCad/share/kicad/library/power
LibName107=S:/Program Files/KiCad/share/kicad/library/Power_Management
LibName108=S:/Program Files/KiCad/share/kicad/library/powerint
LibName109=S:/Program Files/KiCad/share/kicad/library/pspice
LibName110=S:/Program Files/KiCad/share/kicad/library/references
LibName111=S:/Program Files/KiCad/share/kicad/library/regul
LibName112=S:/Program Files/KiCad/share/kicad/library/relays
LibName113=S:/Program Files/KiCad/share/kicad/library/rfcom
LibName114=S:/Program Files/KiCad/share/kicad/library/RFSolutions
LibName115=S:/Program Files/KiCad/share/kicad/library/sensors
LibName116=S:/Program Files/KiCad/share/kicad/library/silabs
LibName117=S:/Program Files/KiCad/share/kicad/library/siliconi
LibName118=S:/Program Files/KiCad/share/kicad/library/stm8
LibName119=S:/Program Files/KiCad/share/kicad/library/stm32
LibName120=S:/Program Files/KiCad/share/kicad/library/supertex
LibName121=S:/Program Files/KiCad/share/kicad/library/switches
LibName122=S:/Program Files/KiCad/share/kicad/library/texas
LibName123=S:/Program Files/KiCad/share/kicad/library/transf
LibName124=S:/Program Files/KiCad/share/kicad/library/transistors
LibName125=S:/Program Files/KiCad/share/kicad/library/triac_thyristor
LibName126=S:/Program Files/KiCad/share/kicad/library/ttl_ieee
LibName127=S:/Program Files/KiCad/share/kicad/library/valves
LibName128=S:/Program Files/KiCad/share/kicad/library/video
LibName129=S:/Program Files/KiCad/share/kicad/library/wiznet
LibName130=S:/Program Files/KiCad/share/kicad/library/Worldsemi
LibName131=S:/Program Files/KiCad/share/kicad/library/Xicor
LibName132=S:/Program Files/KiCad/share/kicad/library/xilinx
LibName133=S:/Program Files/KiCad/share/kicad/library/zetex
LibName134=S:/Program Files/KiCad/share/kicad/library/Zilog
